pub struct Wireguard {}

impl Wireguard {
    pub fn new() -> Self {
        Self {}
    }

    pub fn write_config(&self) {
        let template = format!(
            r"
# Generated by mcsync
# DO NOT TOUCH - Will be overriden anyway.

[Interface]
PrivateKey = {}
Address = {}
ListenPort = 51820

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
",
            "", ""
        );
    }
}
